### ISSUE TITLE
Possibility to Init a JSON using a dictionary

### ISSUE THREAD

**Issue by vitorhugods** [Beyova/BeyovaJSON#1]
In 0.0.3, it was possible to do so, by using:

`JToken([String: Any])`

Now, the only thing that I've found, in 0.0.5 was:

`JSON(dictionaryLiteral: (String, Any) ...)` which does not support a full dictionary

And so far, Swift [currently does not support Splatting](https://bugs.swift.org/browse/SR-128).

Is there a way that I've not found to init a JSON using a dictionary in 0.0.5?

Thanks!

**Comment by vitorhugods** [comment]
I could initalize the JSON by changing the init to public.

```swift
//
//  JSON.swift
//  BeyovaJSON
//
//  Copyright © 2018 Beyova. All rights reserved.
//

import Foundation

public struct JSON {
    
    public private(set) var value: Any
    
    init() {
        self.value = NSNull()
    }
    
    public init(_ value: Any?) { //Public
        if let val = value {
            self.value = val
        }
        else {
            self.value = NSNull()
        }
    }
}
```


So it is possible to just `JSON(dictionary)`

**Comment by canius** [comment]
@vitorhugods Thanks for your feedback. Updated in 0.0.6
